/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* The file associated with an asset or format
*/
export class AssetFile {
    /**
    * the name of the file
    */
    'name': string;
    /**
    * A URL address to the file content
    */
    'source': string;
    /**
    * the http Content-Type used with the file
    */
    'contentType': string;
    /**
    * The size of the file in bytes
    */
    'size': number;
    /**
    * The width of the file
    */
    'width'?: number;
    /**
    * The height of the file
    */
    'height'?: number;
    /**
    * The duration of the file in seconds
    */
    'duration'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number"
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AssetFile.attributeTypeMap;
    }
}

