/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* The information required to start the workflow to create or update an asset
*/
export class AssetCreate {
    'url': string;
    /**
    * The unique id of the asset
    */
    'assetId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AssetCreate.attributeTypeMap;
    }
}

