/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* The state of a single job
*/
export class Job {
    /**
    * The unique id of the job
    */
    'id': string;
    /**
    * The state of the job
    */
    'state': Job.StateEnum;
    /**
    * The asset that this job is processing work for
    */
    'assetId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "Job.StateEnum"
        },
        {
            "name": "assetId",
            "baseName": "asset_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Job.attributeTypeMap;
    }
}

export namespace Job {
    export enum StateEnum {
        Queued = <any> 'queued',
        Processing = <any> 'processing',
        Failed = <any> 'failed',
        Completed = <any> 'completed',
        Cancelled = <any> 'cancelled'
    }
}
