/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Task } from './task';

/**
* The task information for a workflow
*/
export class JobCreate {
    'tasks'?: Task;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Task"
        }    ];

    static getAttributeTypeMap() {
        return JobCreate.attributeTypeMap;
    }
}

