/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* The kind of media
*/
export enum Kind {
    Image = <any> 'image',
    Video = <any> 'video',
    Audio = <any> 'audio',
    Text = <any> 'text',
    Unknown = <any> 'unknown'
}
