/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* a task to perform on an asset
*/
export class Tasks {
    /**
    * The name of the task
    */
    'task'?: string;
    /**
    * An array of arguments to use for the task, if left empty will use the results of the previous task. must match the expected arguments for the requested task.
    */
    'args'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "task",
            "baseName": "task",
            "type": "string"
        },
        {
            "name": "args",
            "baseName": "args",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Tasks.attributeTypeMap;
    }
}

