/**
 * Open DAM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

/**
* version data of an asset
*/
export class Version {
    /**
    * The version number
    */
    'number': number;
    /**
    * A point in time represented as milliseconds from the Epoch (UTC)
    */
    'timestamp': number;
    'jobId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "number"
        },
        {
            "name": "jobId",
            "baseName": "job_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Version.attributeTypeMap;
    }
}

