name: Release Workflow
on:
  release:
    types: [published]

jobs:
  release-client:
    env:
      REF: ${{ github.ref }}
    name: Release Node Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@open-dam"

      - name: Build Client
        run: |
          npm install
          npm run build

      - name: Publish Client
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "open-dam"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}
